roboat/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'wellcome/index'

  devise_scope :user do
    authenticated :user do
      root 'collects#new', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get 'collects/:id/receive_measure_0' => 'collects#receive_measure_0'
  get 'collects/:id/receive_measure_1' => 'collects#receive_measure_1'
  get 'collects/:id/receive_measure_2' => 'collects#receive_measure_2'
  get 'collects/:id/left' => 'collects#left'
  get 'collects/:id/right' => 'collects#right'
  get 'collects/:id/forward' => 'collects#forward'
  get 'collects/:id/back' => 'collects#back'

  resources :collects
  resources :measures
  resources :boats
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

roboat/app/models/boat.rb
class Boat < ApplicationRecord
  has_many :users
end

roboat/app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :set_boat, only: [:show, :edit, :update, :destroy]

  # GET /boats
  # GET /boats.json
  def index
    @boats = Boat.all
  end

  # GET /boats/1
  # GET /boats/1.json
  def show
  end

  # GET /boats/new
  def new
    @boat = Boat.new
  end

  # GET /boats/1/edit
  def edit
  end

  # POST /boats
  # POST /boats.json
  def create
    @boat = Boat.new(boat_params)

    respond_to do |format|
      if @boat.save
        format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
        format.json { render :show, status: :created, location: @boat }
      else
        format.html { render :new }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boat
      @boat = Boat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_params
      params.require(:boat).permit(:battery_status, :speed, :compass)
    end
end

roboat/app/helpers/boats_helper.rb
module BoatsHelper
end

roboat/app/views/boats/_form.html.erb
<%= form_for(boat) do |f| %>
  <% if boat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boat.errors.count, "error") %> prohibited this boat from being saved:</h2>

      <ul>
      <% boat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :battery_status %>
    <%= f.text_field :battery_status %>
  </div>

  <div class="field">
    <%= f.label :speed %>
    <%= f.text_field :speed %>
  </div>

  <div class="field">
    <%= f.label :compass %>
    <%= f.text_field :compass %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

roboat/app/views/boats/edit.html.erb
<h1>Editing Boat</h1>

<%= render 'form', boat: @boat %>

<%= link_to 'Show', @boat %> |
<%= link_to 'Back', boats_path %>

roboat/app/views/boats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boats</h1>

<table>
  <thead>
    <tr>
      <th>Battery status</th>
      <th>Speed</th>
      <th>Compass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boats.each do |boat| %>
      <tr>
        <td><%= boat.battery_status %></td>
        <td><%= boat.speed %></td>
        <td><%= boat.compass %></td>
        <td><%= link_to 'Show', boat %></td>
        <td><%= link_to 'Edit', edit_boat_path(boat) %></td>
        <td><%= link_to 'Destroy', boat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boat', new_boat_path %>

roboat/app/views/boats/new.html.erb
<h1>New Boat</h1>

<%= render 'form', boat: @boat %>

<%= link_to 'Back', boats_path %>

roboat/app/views/boats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Battery status:</strong>
  <%= @boat.battery_status %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @boat.speed %>
</p>

<p>
  <strong>Compass:</strong>
  <%= @boat.compass %>
</p>

<%= link_to 'Edit', edit_boat_path(@boat) %> |
<%= link_to 'Back', boats_path %>