roboat/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'wellcome/index'

  devise_scope :user do
    authenticated :user do
      root 'collects#new', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get 'collects/:id/receive_measure_0' => 'collects#receive_measure_0'
  get 'collects/:id/receive_measure_1' => 'collects#receive_measure_1'
  get 'collects/:id/receive_measure_2' => 'collects#receive_measure_2'
  get 'collects/:id/left' => 'collects#left'
  get 'collects/:id/right' => 'collects#right'
  get 'collects/:id/forward' => 'collects#forward'
  get 'collects/:id/back' => 'collects#back'

  resources :collects
  resources :measures
  resources :boats
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

roboat/app/models/measure.rb
class Measure < ApplicationRecord
  belongs_to :collect, required: false
end

roboat/app/controllers/measures_controller.rb
class MeasuresController < ApplicationController
  before_action :set_measure, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /measures
  # GET /measures.json
  def index
    @measures = Measure.all
  end

  # GET /measures/1
  # GET /measures/1.json
  def show
  end

  # GET /measures/new
  def new
    @measure = Measure.new
  end

  # GET /measures/1/edit
  def edit
  end

  # POST /measures
  # POST /measures.json
  def create
    @measure = Measure.new(measure_params)

    respond_to do |format|
      if @measure.save
        format.html { redirect_to @measure, notice: 'Measure was successfully created.' }
        format.json { render :show, status: :created, location: @measure }
      else
        format.html { render :new }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measures/1
  # PATCH/PUT /measures/1.json
  def update
    respond_to do |format|
      if @measure.update(measure_params)
        format.html { redirect_to @measure, notice: 'Measure was successfully updated.' }
        format.json { render :show, status: :ok, location: @measure }
      else
        format.html { render :edit }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measures/1
  # DELETE /measures/1.json
  def destroy
    @measure.destroy
    respond_to do |format|
      format.html { redirect_to measures_url, notice: 'Measure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measure
      @measure = Measure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measure_params
      params.require(:measure).permit(:ph, :turbidity, :temperature, :conductivity, :latitude, :longitude)
    end
end

roboat/app/helpers/measures_helper.rb
module MeasuresHelper
end

roboat/app/views/measures/_form.html.erb
<%= form_for(measure) do |f| %>
  <% if measure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(measure.errors.count, "error") %> prohibited this measure from being saved:</h2>

      <ul>
      <% measure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ph %>
    <%= f.text_field :ph %>
  </div>

  <div class="field">
    <%= f.label :turbidity %>
    <%= f.text_field :turbidity %>
  </div>

  <div class="field">
    <%= f.label :temperature %>
    <%= f.text_field :temperature %>
  </div>

  <div class="field">
    <%= f.label :conductivity %>
    <%= f.text_field :conductivity %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

roboat/app/views/measures/edit.html.erb
<h1>Editing Measure</h1>

<%= render 'form', measure: @measure %>

<%= link_to 'Show', @measure %> |
<%= link_to 'Back', measures_path %>

roboat/app/views/measures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Measures</h1>

<table>
  <thead>
    <tr>
      <th>Ph</th>
      <th>Turbidity</th>
      <th>Temperature</th>
      <th>Conductivity</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @measures.each do |measure| %>
      <tr>
        <td><%= measure.ph %></td>
        <td><%= measure.turbidity %></td>
        <td><%= measure.temperature %></td>
        <td><%= measure.conductivity %></td>
        <td><%= measure.latitude %></td>
        <td><%= measure.longitude %></td>
        <td><%= link_to 'Show', measure %></td>
        <td><%= link_to 'Edit', edit_measure_path(measure) %></td>
        <td><%= link_to 'Destroy', measure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Measure', new_measure_path %>

roboat/app/views/measures/new.html.erb
<h1>New Measure</h1>

<%= render 'form', measure: @measure %>

<%= link_to 'Back', measures_path %>

roboat/app/views/measures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ph:</strong>
  <%= @measure.ph %>
</p>

<p>
  <strong>Turbidity:</strong>
  <%= @measure.turbidity %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @measure.temperature %>
</p>

<p>
  <strong>Conductivity:</strong>
  <%= @measure.conductivity %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @measure.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @measure.longitude %>
</p>

<%= link_to 'Edit', edit_measure_path(@measure) %> |
<%= link_to 'Back', measures_path %>