roboat/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'wellcome/index'

  devise_scope :user do
    authenticated :user do
      root 'collects#new', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get 'collects/:id/receive_measure_0' => 'collects#receive_measure_0'
  get 'collects/:id/receive_measure_1' => 'collects#receive_measure_1'
  get 'collects/:id/receive_measure_2' => 'collects#receive_measure_2'
  get 'collects/:id/left' => 'collects#left'
  get 'collects/:id/right' => 'collects#right'
  get 'collects/:id/forward' => 'collects#forward'
  get 'collects/:id/back' => 'collects#back'

  resources :collects
  resources :measures
  resources :boats
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

roboat/app/models/collect.rb
class Collect < ApplicationRecord
  has_many :measures
  accepts_nested_attributes_for :measures
end

roboat/app/controllers/collects_controller.rb
class CollectsController < ApplicationController
  before_action :set_collect, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /collects
  # GET /collects.json
  def index
    @collects = Collect.all
  end

  # GET /collects/1
  # GET /collects/1.json
  def show
  end

  # GET /collects/new
  def new
    @collect = Collect.new
    @collect.measures.build
    @collect.measures.build
    @collect.measures.build
  end

  # GET /collects/1/edit
  def edit
    connect_serial
    @serialport.write('1')
    read_value = build_full_message
    puts "VALOR DA LOCALIZACAO = " + read_value
    cookies['roboat_location'] = {
        :value => read_value
    }
    # receive_data_from_xbee
  end

  def connect_serial
    @serialport = Serial.new '/dev/ttyACM0' # Defaults to 9600 baud, 8 data bits, and no parity
    # @serialport = Serial.new '/dev/ttyACM0' # Defaults to 9600 baud, 8 data bits, and no parity
  end

  def receive_measure_0
    connect_serial
    @serialport.write('1')
    read_value = build_full_message
    puts read_value
    cookies['measure_0'] = {
        :value => read_value
    }
  end

  def receive_measure_1
    connect_serial
    @serialport.write('1')
    read_value = build_full_message
    cookies['measure_1'] = {
        :value => read_value
    }
  end

  def receive_measure_2
    connect_serial
    @serialport.write('1')
    read_value = build_full_message
    cookies['measure_2'] = {
        :value => read_value
    }
  end

  def left
    connect_serial
    @serialport.write('a')
  end

  def right
    connect_serial
    @serialport.write('d')
  end

  def back
    connect_serial
    @serialport.write('s')
  end

  def forward
    connect_serial
    @serialport.write('w')
  end

  def build_full_message
    read_value = ""
    for i in 0..5
      read_value += @serialport.read(100)
      sleep 1
    end
    print "last read_value = " + read_value
    read_value
  end

  # POST /collects
  # POST /collects.json
  def create
    @collect = Collect.new(collect_params)

    respond_to do |format|
      if @collect.save
        format.html { redirect_to edit_collect_path(@collect), notice: 'Coleta foi criada com sucesso.' }
        format.json { render :edit, status: :created, location: @collect }
      else
        format.html { render :new }
        format.json { render json: @collect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collects/1
  # PATCH/PUT /collects/1.json
  def update
    respond_to do |format|
      if @collect.update(collect_params)
        format.html { redirect_to @collect, notice: 'Collect was successfully updated.' }
        format.json { render :show, status: :ok, location: @collect }
      else
        format.html { render :edit }
        format.json { render json: @collect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collects/1
  # DELETE /collects/1.json
  def destroy
    @collect.destroy
    respond_to do |format|
      format.html { redirect_to collects_url, notice: 'Coleta foi removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_collect
    @collect = Collect.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def collect_params
    params.require(:collect).permit(:title, measures_attributes: [:ph, :conductivity, :temperature, :latitude, :longitude, :turbidity, :id])
  end
end

roboat/app/helpers/collects_helper.rb
module CollectsHelper
end

roboat/app/views/collects/_edit_form.html.erb
<%= form_for(collect) do |f| %>
  <% if collect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collect.errors.count, "error") %> prohibited this collect from being saved:</h2>

      <ul>
      <% collect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Título" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>


<ol>

<%=  f.fields_for  :measures do |measure_form| %>

<li class="collect-group">
  <p>Amostra: </p>
  <div class="form-group">
    <%= measure_form.label :ph, "pH" %>
    <%= measure_form.text_field :ph %>
  </div>

  <div class="form-group">
    <%= measure_form.label :turbidity %>
    <%= measure_form.text_field :turbidity %>
  </div>

  <div class="form-group">
    <%= measure_form.label :temperature %>
    <%= measure_form.text_field :temperature %>
  </div>

  <div class="form-group">
    <%= measure_form.label :conductivity %>
    <%= measure_form.text_field :conductivity %>
  </div>


<div class="row">
  <div class="form-group col-md-6">
    <%= measure_form.label :latitude%>
    <%= measure_form.text_field :latitude, class: "form-control" %>
  </div>

  <div class="form-group col-md-6">
    <%= measure_form.label :longitude %>
    <%= measure_form.text_field :longitude, class: "form-control"  %>
  </div>
</div>

</li>

<% end %>
</ol>

  <div class="actions">
    <%= f.submit "Enviar", class: 'btn btn-success' %>
  </div>
<% end %>

roboat/app/views/collects/_form.html.erb
<%= form_for(collect) do |f| %>
  <% if collect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collect.errors.count, "error") %> prohibited this collect from being saved:</h2>

      <ul>
      <% collect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Título" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>


<ol>

<%=  f.fields_for  :measures do |measure_form| %>

<li class="collect-group">
  <p>Amostra: </p>
  <div class="form-group hidden">
    <%= measure_form.label :ph, "pH" %>
    <%= measure_form.text_field :ph %>
  </div>

  <div class="form-group hidden">
    <%= measure_form.label :turbidity %>
    <%= measure_form.text_field :turbidity %>
  </div>

  <div class="form-group hidden">
    <%= measure_form.label :temperature %>
    <%= measure_form.text_field :temperature %>
  </div>

  <div class="form-group hidden">
    <%= measure_form.label :conductivity %>
    <%= measure_form.text_field :conductivity %>
  </div>


<div class="row">
  <div class="form-group col-md-6">
    <%= measure_form.label :latitude%>
    <%= measure_form.text_field :latitude, class: "form-control" %>
  </div>

  <div class="form-group col-md-6">
    <%= measure_form.label :longitude %>
    <%= measure_form.text_field :longitude, class: "form-control"  %>
  </div>
</div>

</li>

<% end %>
</ol>

  <div class="actions">
    <%= f.submit "Enviar", class: 'btn btn-success send-info' %>
  </div>
<% end %>

roboat/app/views/collects/edit.html.erb
<div id="sidebar-wrapper">
  <div class="row">
    <h1>Monitorar Coleta</h1>
    <div class="col-md-12">
      <%= render 'edit_form', collect: @collect %>
    </div>
  </div>
</div>

<div class="controles">
  <button type="button" class="btn btn-info btn-left" onclick="left()">
    <span class="glyphicon glyphicon-arrow-left"></span>
  </button>
  <button type="button" class="btn btn-info btn-up" onclick="forward()">
    <span class="glyphicon glyphicon-arrow-up"></span>
  </button>
  <button type="button" class="btn btn-info btn-down" onclick="back()">
    <span class="glyphicon glyphicon-arrow-down"></span>
  </button>
  <button type="button" class="btn btn-info btn-right" onclick="right()">
    <span class="glyphicon glyphicon-arrow-right"></span>
  </button>
  </button>
  <button type="button" class="btn btn-success btn-collect">
    <span class="glyphicon glyphicon-download-alt"></span>
  </button>
</div>

<a href="#menu-toggle" class="btn btn-default " id="menu-toggle">
  <span class="glyphicon glyphicon-menu-hamburger" id="menu-icon" aria-hidden="true"></span>
</a>

<div id="map"></div>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAaQjjH5bKQZa5VQtSm6gUIIxD8xJRN8ss&callback=initMap&libraries=geometry"
type="text/javascript"></script>

<%= javascript_include_tag 'sidebar' %>
<%= javascript_include_tag 'cookie_manager' %>
<%= javascript_include_tag 'monitor_map' %>

roboat/app/views/collects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coletas Existentes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    
</table>  
  <div id="table" class="table-editable">
    <table class="table">
        <th>Nome</th>
  </thead>

  <tbody>
    <% @collects.each do |collect| %>
      <tr>
        <td><%= collect.title %></td>
        <td><%= link_to 'Detalhar', collect %></td>
        <td>
          <span class="table-up glyphicon glyphicon-arrow-up"></span>
          <span class="table-down glyphicon glyphicon-arrow-down"></span>
        <%= link_to 'Editar', edit_collect_path(collect) %>
        </td>
        <td>
           <span class="table-remove glyphicon glyphicon-remove"></span>
        <%= link_to 'Remover', collect, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
 
        </td>
      </tr>
      <!-- This is our clonable table line -->
      <tr class="hide">
        <td>
          <span class="table-remove glyphicon glyphicon-remove"></span>
        </td>
        <td>
          <span class="table-up glyphicon glyphicon-arrow-up"></span>
          <span class="table-down glyphicon glyphicon-arrow-down"></span>
        </td>
      </tr>
    </table>
  </div>
  
<%= link_to 'Nova Coleta', new_collect_path %>

</div>

roboat/app/views/collects/new.html.erb
<div id="sidebar-wrapper">
  <div class="row">
    <h1>Nova Coleta</h1>
    <div class="col-md-12">
      <%= render 'form', collect: @collect %>
    </div>
  </div>
</div>

<a href="#menu-toggle" class="btn btn-default " id="menu-toggle">
  <span class="glyphicon glyphicon-menu-hamburger" id="menu-icon" aria-hidden="true"></span>
</a>

<input  class="btn btn-xs btn-danger delete-location" onclick="deleteLastMarker();" type=button value="Deletar última localização">

<div id="map"></div>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAaQjjH5bKQZa5VQtSm6gUIIxD8xJRN8ss&callback=initMap&libraries=geometry"
type="text/javascript"></script>



<%= javascript_include_tag 'sidebar' %>
<%= javascript_include_tag 'new_map' %>

roboat/app/views/collects/show.html.erb
<% if notice %>

  <div class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <%= notice %>
  </div>

<% end %>

<div class="col-lg-12" style="margin-top: 50px;">
  <div class="panel panel-default" style="padding-left: 0;">
    <div class="panel-heading">
      <%= @collect.title %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">

      <div class="row"><div class="col-sm-12"><table width="100%" class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline" id="dataTables-example" role="grid" aria-describedby="dataTables-example_info" style="width: 100%;">
        <thead>
          <tr role="row">
            <th tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">ID</th>
            <th tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">Latitude</th>
            <th tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Longitude</th>
            <th tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">pH</th>
            <th tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Turbidez</th>
            <th tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Temperatura</th>
            <th tabindex="0" aria-controls="dataTables-example" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Condutividade</th>
          </tr>
        </thead>
        <tbody>

          <%if @collect.measures.present? %>
            <% i=0 %>
            <%@collect.measures.each do |measure| %>
            <tr class="gradeA odd" role="row">
              <td class="id-<%= i %>"><strong><%= measure.id %>. </strong></td>
              <td class="latitude"><%= measure.latitude %></td>
              <td class="longitude"><%= measure.longitude %></td>
              <td class="ph"><%= measure.ph %></td>
              <td class="turbidity"><%= measure.turbidity %></td>
              <td class="temperature"><%= measure.temperature %></td>
              <td class="conductivity"><%= measure.conductivity %></td>
            </tr>
            <% i=i+1 %>
            <% end %>
          <%end%>

        </tbody>
      </table>
    </div>
  </div>

</div>
<!-- /.panel-body -->
</div>
<!-- /.panel -->



<div id="measure_chart" style="height: 250px;"></div>




</div>

<%= link_to 'Edit', edit_collect_path(@collect) %> |
<%= link_to 'Back', collects_path %>


<script type="text/javascript">
new Morris.Bar({
// ID of the element in which to draw the chart.
  element: 'measure_chart',
  // Chart data records -- each entry in this array corresponds to a point on
  // the chart.
  data: [
    {
      parameter: 'pH',
      measure_1: $(".ph")[0].innerHTML,
      measure_2: $(".ph")[1].innerHTML,
      measure_3: $(".ph")[2].innerHTML },
    {
      parameter: 'Turbidez',
      measure_1: $(".turbidity")[0].innerHTML,
      measure_2: $(".turbidity")[1].innerHTML,
      measure_3: $(".turbidity")[2].innerHTML},
    {
      parameter: 'Temperatura',
      measure_1: $(".temperature")[0].innerHTML,
      measure_2: $(".temperature")[1].innerHTML,
      measure_3: $(".temperature")[2].innerHTML},
    {
      parameter: 'Condutividade',
      measure_1: $(".conductivity")[0].innerHTML,
      measure_2: $(".conductivity")[1].innerHTML,
      measure_3: $(".conductivity")[2].innerHTML}
  ],
  // The name of the data record attribute that contains x-values.
  xkey: 'parameter',
  // A list of names of data record attributes that contain y-values.
  ykeys: ['measure_1', 'measure_2', 'measure_3' ],
  // Labels for the ykeys -- will be displayed when you hover over the
  // chart.
  labels: ['Medição ' + $(".id-0").text(), 'Medição ' + $(".id-1").text(), 'Medição ' + $(".id-2").text()]
});
</script>